version: '3.8'

services:
  # Next.js Service
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app          # Mount your local code to the container
      - /app/node_modules  # Avoid overwriting node_modules
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/nextcord_db
      - WATCHPACK_POLLING=true
    command: npm run dev  # Start the Next.js dev server
    container_name: nextcord

  # PostgreSQL Service
  postgres:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistent data storage
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nextcord_db
    ports:
      - "5432:5432"  # Expose PostgreSQL port

volumes:
  postgres-data:  # Volume for persisting PostgreSQL data