version: '3.8'

services:
  # Next.js Service
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/nextcord_db
      - WATCHPACK_POLLING=true
    command: npm run dev
    container_name: nextcord

  # PostgreSQL Service
  postgres:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nextcord_db
    ports:
      - "5432:5432"

volumes:
  postgres-data:  # Volume for persisting PostgreSQL data